language: java

before_install:
  - chmod +x .travis/*.sh
  - .travis/load_gpg.sh

install:
  - mvn clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/script.sh

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  skip_cleanup: true
  name: $project_version
  draft: true
  api_key:
    secure: RJs2JHiBn0+bIJyYRzgjVd7kz8xs8Klh32IRlEHUqqZIClTANAVAjt+3XQjKAG9qOIoeNpDioZouCC3t4gz7+3khpCgFgh3Aj3oVypeb09r0rfmyoO4+BMZ0+/YfKIJrTe5vQ8h/4fgHip5vQInKjgNSF1Bsvwp/jqvfAyY57nClhxk6Rggi8nsKCd7CERuRAd5U8beZb0u1mi+pja4lH3hCpRGHRzZfVyfraK76Z21FgNAGPfjS7rjhD2vCsBg1qkKLn1cHPqcVAuDHDAVNZHKz6dSuT5IqkvHksPOVo12AlBW0HR1fTIHYRQJycWo1b5ZQIaNHRzVf9lPxJtpgQezfkfe4KNFIMCZ881MvOBVo5AyAUCHAtjjnGe639Sq/2WnfUr9sHckzH5PUcYE5cHd1ZxTenv/ixv7p3ijC+iMhRO8+t5DSWolD+rFDXWWCKxwKhwHgBJezc14vEofFGoZoTQBVPONAswRCXuNCqbwaIk7M+KWSjhzPfYSu0Hv8/9Nn61ObhGnrowqgheCUIuzlymOoshfneJgkn9ArbE90ZuXV4gUGUtICGDeYBonXvTbgYCrCMsMzZGc59bZH7Yc/BHb52LiknmrZRD+dZwJESmRNcQsFuBqoYDtwkpGnu8j+jU72xmmPFy3SedtSf0w13XUxdafg73d1PIVgbrE=
  file:
    - target/zeroconf-java-jar-with-dependencies.jar
  on:
    repo: devgianlu/zeroconf-java
    branch: master
    tags: true

cache:
  directories:
    - ~/.m2/repository
